apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}